# Task 2 Sketch the Lagrange polynomials
from matplotlib import pyplot as plt
import numpy as np

def lagrange(i, points, X):
  """Get value of the i:th lagrange poynomial generated by the list
  of "points". All evaluated at all values in X 
  """
  res = []
  help = 1
  for j in range(len(X)):
    for k in range(len(points)):
      if k != i:
        help *= (X[j] - points[k]) / (points[i] - points[k])
    res.append(help)
    help = 1
  return res


if __name__ == "__main__":
    X = np.linspace(-1, 1, 100)
    points = []
    n = 4
    for k in range(n):
      points.append(np.cos((2*(k+1) - 1)/float(2*n) * np.pi))
              
    for i in range(len(points)):
      L = lagrange(i, points, X)
      plt.plot(X, L)
                      
    #plt.legend(["$l_0$", "$l_1$", "$l_2$"])
    plt.savefig("task_3.png")

